---
language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS repo2_test;" -uroot; fi

script: phpunit --configuration phpunit_$DB.xml --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
